name: publish-ecr-action

author: Heron Labs

description: Publish ECR

inputs:
  AWS_ROLE_TO_ASSUME:
    description: inputs.AWS_ROLE_TO_ASSUME
    required: true
  AWS_REGION:
    description: inputs.AWS_REGION
    required: true
  AWS_ROLE_DURATION_SECONDS:
    description: inputs.AWS_ROLE_DURATION_SECONDS
    required: true
  AWS_REPOSITORY:
    description: inputs.AWS_REPOSITORY
    required: true
  BUILD_NAME:
    description: inputs.BUILD_NAME
    required: true
  FILE_NAME:
    description: inputs.FILE_NAME
    required: true
  TAG_NAME:
    description: inputs.TAG_NAME
    required: true

runs:
  using: composite
  steps:
    - name: '[BUILD] | Build'
      run: docker build --tag ${{ inputs.BUILD_NAME }}:${{ inputs.TAG_NAME }} . -f ${{ inputs.FILE_NAME }}
      shell: bash

    - name: '[TEST] | Lint Check'
      run: docker run --rm --interactive hadolint/hadolint < ${{ inputs.FILE_NAME }}
      shell: bash

    - name: '[PUBLISH] | Configure AWS Credentials'
      uses: aws-actions/configure-aws-credentials@v5
      with:
        aws-region: ${{ inputs.AWS_REGION }}
        role-to-assume: ${{ inputs.AWS_ROLE_TO_ASSUME }}
        role-duration-seconds: ${{ inputs.AWS_ROLE_DURATION_SECONDS }}
        role-session-name: publish-ecr-action-session

    - name: '[PUBLISH] | Login on ECR'
      uses: aws-actions/amazon-ecr-login@v2

    - name: '[PUBLISH] | Publish image on ECR'
      shell: bash
      run: |
        chmod +x ./publish-ecr-action/core/publish-ecr-image.sh
        ./publish-ecr-action/core/publish-ecr-image.sh
      env:
        AWS_REPOSITORY: ${{ inputs.AWS_REPOSITORY }}
        BUILD_NAME: ${{ inputs.BUILD_NAME }}
        TAG_NAME: ${{ inputs.TAG_NAME }}
